name: creating users
on: 
schedule:
    - cron: '*/360 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Create users
        uses: cypress-io/github-action@v6
